### PR TITLE
update to .net standard

### PR DESCRIPTION
**Pull request by jinhong-**

### CODE REVIEW

**Comment by DmitrySikorsky** [comment]
Hi! The reason why I still didn't merge this PM is because I'm not sure how to be with versions. I think it will be breaking change because users will have to update their .csproj files to add some references, because now Microsoft.AspNetCore.All is just added everywhere. What do you think about that? Should this fix be applied in the next major release? Like 4.0.0.

**Comment by treefishuk** [comment]
Created a branch to do just this then discovered @jinhong- had done it already. I look forward to this being applied to the next release.

**Comment by treefishuk** [comment]
Are you sure?? Looking at this :

https://www.nuget.org/packages/Microsoft.NETCore.App/

.netcoreapp2.1 looks as tho it has a dependency on standard >= 2.0.3 

So it should be supported unless I’m reading it wrong?...

**Comment by jinhong-** [comment]
Sorry that i didn't reply.. actually somebody already created a fork to fix this. I merely copied his codes to do a PR

**Comment by Xarkam** [comment]
@treefishuk I refer from the doc: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md

**Comment by treefishuk** [comment]
For me all I really need is the abstraction projects converted so my domain entities and repository interfaces can be created using .net standard projects. Have created new pull request https://github.com/ExtCore/ExtCore/pull/110

**Comment by DmitrySikorsky** [comment]
So, I agree that the basic abstract projects should rely on netstandard2.0 (not 2.1: https://github.com/dotnet/standard/issues/682) instead of netcoreapp2.1. And that was my mistake to use netcoreapp2.1 in that cases. I think that data access projects and some others should do this way as well.

But some of the projects (ExtCore.WebApplication and ExtCore.Mvc.*) can't, because they use features that are related only to web applications and aren't part of the netstandard2.0. Am I correct?

**Comment by treefishuk** [comment]
That’s certainly the conclusion that I came to.

**Pull request closed without merging**
