### PR TITLE
Added MySQL provider (using Pomelo)

### PR DESCRIPTION
**Pull request by cmjchrisjones**
Updated to use latest SDK
Added MySQL provider (using Pomelo)

### CODE REVIEW

**Comment by DmitrySikorsky** [comment]
Hi! Thank you for the pull request, I will reply ASAP.

**Comment by DmitrySikorsky** [comment]
Could you please tell why you have chosen Pomelo, not an official one (https://docs.microsoft.com/en-us/ef/core/providers/mysql/) ? Thanks.

**Comment by cmjchrisjones** [comment]
Hi @DmitrySikorsky, reason I used Pomelo rather than the official one was because I had some issues with it in another project, the Pomelo one seemed to be a bit further ahead.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/112, there is a table towards the bottom of this conversation comparing Pomelo with the Oracle and Sapient equivalents.

**Comment by KANekT** [comment]
I think package name correct is ExtCore.Data.Pomelo.MySql.

**Comment by DmitrySikorsky** [comment]
So, the reason that I still haven't merged the PR is that I don't know how to do this better. My thoughts are the following:

1. I want to be able to add official implementation later, and it should have name ExtCore.Data.EntityFramework.MySql because it is the most obvious. Right?

2. I still want people to add other implementations of the MySQL and other DBs.

3. Pomelo still uses EF, so there should be EntityFramework in the package name. Agree?

4. In this case I think the best package name is something like

ExtCore.Data.EntityFramework.Pomelo.MySql

Maybe ExtCore.Data.EntityFramework.MySql.Pomelo might be a good choice too, but in case when the third party provider provides different DB support I think it would be better to have EntityFramework.Provider.DB template.

@cmjchrisjones, if you agree with me, please, update your PR to follow this naming convention. And also please add headers to all the created files. And please take a look at the formatting to make it as close to the project's one as possible. I will help you to format the rest when the PR is merged. Sorry that we have wasted your time with this names and thank you for your contribution!

**Pull request closed without merging**
