### PR TITLE
Updated Abstraction and Data projects to .net Standard

### PR DESCRIPTION
**Pull request by treefishuk**
Expanding on the pull request https://github.com/ExtCore/ExtCore/pull/110 this implements the conversion of the majority of projects to .net standard which works with the update to core 2.1.

### CODE REVIEW

**Comment by DmitrySikorsky** [comment]
Thank you, I will review the commits.

**Comment by DmitrySikorsky** [comment]
@treefishuk, please take a look at my last comment on #110. Thank you.

**Comment by Xarkam** [comment]
Can switching to .net standard have any influence on the AntiForgeryToken mechanism from Razor ?

**Comment by treefishuk** [comment]
This pull request would not affect it no. The AntiForgeyToken would be be used in the the MVC projects which have been left as .net core 2.1.

**Comment by DmitrySikorsky** [comment]
Fixed in a295b35. @treefishuk sorry that it took so much time for me. I partially used your code, it was simpler just to fix current version, than fix conflicts.

**Pull request closed without merging**
