### PR TITLE
Fix #34 - Refactor ExtCore.Data.Models.Abstractions to ExtCore.Data.Entities.Abstractions

### LINKED ISSUE #34: Rename ExtCore.Data.Models.Abstractions with ExtCore.Data.Entities.Abstractions
Because it is not real models, but just entities, DTO.

### PR DESCRIPTION
**Pull request by bdparrish**
1. Replaced all occurrences of `ExtCore.Data.Models.Abstractions` with `ExtCore.Data.Entities.Abstractions`.  This required a local NuGet repository since the package name changed as well.
2. Updated `RepositoryBase` to set the `IStorageContext` in the constructor instead of `SetStorageContext`.  Methods have been marked `Obsolete`.

### CODE REVIEW

**Comment by DmitrySikorsky** [comment]
Thank you! How do you think, how should we do in this case. If I merge your pull request now we will need to change the major version (we will have 2.0.0), because this will change the public API of our framework. How do you think, should we do that now? From another side, I don't think we have anything to fix that will not change the public API for now... So maybe it is good idea.

**Comment by bdparrish** [comment]
Because of the `ObsoleteAttribute` it should be a minor version (1.2.0) in order to give others time to evolve from the old.  The release notes should state such changes and a notification that in the next major release (2.0.0), this method will be removed.

**Comment by bdparrish** [comment]
I would also add that if you don't care about this aspect and want to allow people to use either the previous NuGet version or the new version to get what they want, then you can move it to 2.0.0

**Comment by DmitrySikorsky** [comment]
Yes, I think it is the best choice. Thank you, I will merge soon.

**Pull request closed without merging**
